# Generated by Django 5.1.7 on 2025-04-17 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookStore', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Book',
        ),
    ]
